### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nick-magnini** [hhchen1105/corpus-word2vec#1]
When I try to run the python code for creating word2vec corpus, I'll get segmentation fault if I use `jieba.load_userdict('../var/tw-dict.dict')`

**Comment by hhchen1105** [comment]
The file '[PROJECT-ROOT]/var/tw-dict.dict' is a dictionary used for tokenizing traditional chinese terms.  Users are supposed to provide their own dictionary.

If you are dealing with other languages, you can ignore the code segment.

**Comment by nick-magnini** [comment]
It is exactly on zh wikipedia.

**Comment by hhchen1105** [comment]
You still need to provide your own dictionary to tokenize chinese terms.  

Sample format of the dictionary (one term per line):

鍵盤
上海
黎明
張學友

**Comment by hhchen1105** [comment]
With a proper dictionary and tokenizer, the results look promising.
